//
// Created by zep on 23/05/18.
//

#ifndef SIGNALPROCESSING_JAVA2SIGNALPROCESSINGINTERFACE_H
#define SIGNALPROCESSING_JAVA2SIGNALPROCESSINGINTERFACE_H


class Java2SignalProcessingInterface {

};


#endif //SIGNALPROCESSING_JAVA2SIGNALPROCESSINGINTERFACE_H
